### ISSUE TITLE
i dont know how to get the texture pack for this 

### ISSUE THREAD

**Issue by Flipz98** [Type-32/Minecraft-Modern-Guns-Datapack-Remastered#5]
i can not find the required texture pack for this datapack

**Comment by Type-32** [comment]
Hello **Flipz98**! This datapack is currently under development and I personally would not suggest for you to download it right now, considering that it may cause some significant lag in both singleplayer worlds and multiplayer worlds. However if you really want to play it now, you can get the datapack by simply downloading the files in the "Code" page as a .zip file and go to my other Repository that is titled: "Minecraft MGD Remastered Resource Pack" and download those files also as a .zip file.

**Comment by Type-32** [comment]
After you have those .zip files, load the resource pack and load the datapack both as .zip files and you can play in your world.
